version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD", "sh", "-c", "mysql -h localhost -u root -proot -e 'USE nodedb;' || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 30s
      retries: 15

  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: rafaelgpedroso/node
    container_name: node
    volumes:
      - ./node/main:/usr/src/app/main
    depends_on:
      db:
        condition: service_healthy
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -ltn | grep ':3000' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: rafaelgpedroso/nginx
    container_name: nginx
    networks:
      - minha_rede
    ports:
      - "8080:80"
    depends_on:
      node:
        condition: service_healthy

networks:
  minha_rede:
    driver: bridge