version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    networks:
      - minha_rede
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 3

  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: rafaelgpedroso/node
    container_name: node
    volumes:
      - ./node:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - minha_rede

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: rafaelgpedroso/nginx
    container_name: nginx
    networks:
      - minha_rede
    ports:
      - "8080:80"
    depends_on:
      - node

networks:
  minha_rede:
    driver: bridge